# Using the node alpine image to build the React app
image: node:alpine

# Announce the URL as per CRA docs
# https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#advanced-configuration
variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID 
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY

# Cache node modules - speeds up future builds
cache:
  paths:
  - node_modules

before_script:
  - apk -Uuv add groff less python py-pip
  - pip install awscli

#This declares the pipeline stages  
stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - npm install
    - npm run-script build

test:
  stage: test
  script:
    - echo "Running react test suite......"

deploy:
  stage: deploy
  script:
    - npm run-script deploy
