apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: personal-website
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/issuer: "letsencrypt-prod"
    certmanager.k8s.io/acme-challenge-type: http01
spec:
  tls:
  - hosts:
    - saipathuri.me
    secretName: personal-website-tls
  rules:
  - host: saipathuri.me
    http:
      paths:
      - path: /
        backend:
          serviceName: personal-website
          servicePort: 5000

---

apiVersion: v1
kind: Service
metadata:
  name: personal-website
spec:
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: personal-website

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: personal-website
spec:
  template:
    metadata:
      labels:
        app: personal-website
    spec:
      containers:
      - image: registry.saipathuri.me/saipathuri/personal-website
        name: personal-website
        ports:
        - containerPort: 5000